### ISSUE TITLE
Bug fix for Rhythmbox

### ISSUE THREAD

**Issue by techiespace** [nick-parry/songLyrics#4]
I get the following errors when i run 

> ./songLyrics

 rhythmbox

```
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Rhythmbox was not provided by any .service files
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Rhythmbox was not provided by any .service files

```
And i get - That URL sucked. Giving up now :(
On doing 

> ./songLyrics rhythmbox|rbox

 i get a similar error and the program exits.

**I found a fix for it. Is it okay if i submit a PR?**

**Comment by nick-parry** [comment]
Sorry for the delay. I missed these notifications. Your change looks good. I have merged the PR. Thanks for the fix.
